author: Sunny Guan
keywords: [Markdown]
lang: "en"
titlepage: false
titlepage-text-color: "000000"
titlepage-rule-color: "000000"
titlepage-rule-height: 2
titlepage-background: "../../configs/background3.pdf"
colorlinks: true
header-includes: |
  ```{=latex}
  \usepackage{mathtools}
  \usepackage{tcolorbox}
  \usepackage{xcolor}

  \definecolor{orange}{HTML}{E0862A}
  \definecolor{green}{HTML}{31B300}
  \definecolor{red}{HTML}{F70405}
  \definecolor{blue}{HTML}{1010FE}
  \definecolor{pink}{HTML}{FF69B4}

  \newtcolorbox{mybox}[3][]{
      colback=#2!5,
      colframe=#2!95,
      sharp corners,
      arc=5pt,
      outer arc=5pt,
  }
  \DeclarePairedDelimiter{\abs}{\lvert}{\rvert}

  \newcommand{\lra}{\longrightarrow}
  \newcommand{\Lra}{\Longrightarrow}
  \newcommand{\divs}{\mathrel{\mid}}
  \newcommand{\coprime}{\mathrel{\bot}}
  \newcommand{\squish}{\mathbin{\rightthreetimes}}
  \newcommand{\mods}[1] {\text{  (mod $#1$) }}

  \newcommand{\boxtitle}[2]{\textcolor{#1}{\textbf{#2}  }}
  \newcommand{\boxsubtitle}[2]{\textcolor{#1}{#2}}

  \newenvironment{orange}{\begin{mybox}{orange}}{\end{mybox}}
  \newenvironment{green}{\begin{mybox}{green}}{\end{mybox}}
  \newenvironment{blue}{\begin{mybox}{blue}}{\end{mybox}}
  \newenvironment{red}{\begin{mybox}{red}}{\end{mybox}}
  \newenvironment{pink}{\begin{mybox}{pink}}{\end{mybox}}
  ```
pandoc-latex-environment:
  orange: [orange]
  green: [green]
  blue: [blue]
  red: [red]
  pink: [pink]
